module.exports = {
  extends: 'airbnb',
  rules: {
    'no-console': ['off'],
    'no-alert': ['warn'],
    'import/no-extraneous-dependencies': 'off',
    'import/prefer-default-export': 'warn',
    'newline-per-chained-call': ['error', { ignoreChainWithDepth: 6 }],
    quotes: ['warn'],
    'func-names': ['error', 'never'],
    'space-before-function-paren': ['error', 'never'],
    'comma-dangle': 'off',
    'dot-notation': 'off',
    'arrow-body-style': ['warn', 'as-needed'],
    'prefer-arrow-callback': ['warn'],
    'no-unused-vars': ['warn'],
    'max-len': ['warn', 120],
    'no-trailing-spaces': 'warn',
    'key-spacing': 'warn',
    'arrow-parens': ['warn', 'always'],
    'spaced-comment': 'warn',
    'class-methods-use-this': ['warn'],
    'react/jsx-filename-extension': ['warn', { extensions: ['.js', '.jsx'] }],
    'react/prop-types': ['off'],
    'react/jsx-closing-bracket-location': ['warn', 'after-props'],
    'react/jsx-indent': ['warn'],
    'jsx-a11y/label-has-for': ['off'],
  }
};
